server:
  port: 5002
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilterApi
      routes:
        - id: ms-datos
          uri: http://localhost:5003/
          predicates:
            - Path=/api-datos/**
          #filters:
           # - name: SCGWPreFilter
           # - name: SCGWPostFilter




