server:
  port: 5002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
        - id: ms-datos
          uri: http://localhost:5003/
          predicates:
            - Path=/api-datos/**
        - id: ms-business
          uri: http://localhost:5000/
          predicates:
           - Path=/api-business/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'