
jwt:
  secret: a6e21884876f43819523c31033fa697e

spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

endpoint:
  ms-acceso-datos:
    protocol: http://
    host: localhost
    port: 5003
    base: /api-datos
    parrafos:
      version: /v.1
      url: /parrafo
      name: parrafoCliente
    controlLectura:
      version: /v.1
      url: /controllectura
      name: controlLecturaCliente
    comentariosArt:
      version: /v.1
      url: /comentarioarticulo
      name: comentarioArtCliente
    comentarios:
      version: /v.1
      url: /comentario
      name: comentariosCliente
    articulos:
      version: /v.1
      url: /articulos
      name: articulosCliente
    formato-ideas:
      version: /v.1
      url: /formatoidea
      name: formatoIdeasCliente
    ideas:
      version: /v.1
      url: /ideas
      name: ideasCliente
    personas:
      version: /v.1
      url: /personas
      name: personasCliente
    usuarios:
      version: /v.1
      url: /usuarios
      name: usuariosCliente

repositorio:
  formatoArt:
    ubicacion: C:\\repository\\documentos\\formatos\\
    docDestino: /repository/documentos/articulos/
  formato:
    ubicacion: C:\\repository\\documentos\\formatos\\formato_001.docx


path:
  repo:
    idea: /repository/documentos/usuario/
    comentarios: /repository/documentos/comentario/