
jwt:
  secret: a6e21884876f43819523c31033fa697e

spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

endpoint:
  ms-acceso-datos:
    protocol: http://
    host: localhost
    port: 5003
    base: /api-datos
    articulos:
      version: /v.1
      url: /articulos
      name: articulosCliente
    formato-ideas:
      version: /v.1
      url: /formatoidea
      name: formatoIdeasCliente
    ideas:
      version: /v.1
      url: /ideas
      name: ideasCliente
    personas:
      version: /v.1
      url: /personas
      name: personasCliente
    usuarios:
      version: /v.1
      url: /usuarios
      name: usuariosCliente

repositorio:
  formato:
    ubicacion: C:\\repository\\documentos\\formatos\\formato_001.docx

path:
  repo:
    idea: /repository/documentos/usuario/